version: "3.8"

volumes:
  wireguard:

services:
  wg-easy:
    environment:
      # Seleccion de Idioma:
      # (Idiomas soportados: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, >
      - LANG=es
      # Required:
      # Aquí tu ip pública o nombre de dominio.
      - WG_HOST=84.124.178.137

      # Configuraciones opcionales, a las opciones comentadas se aplicara el valor por defecto:
      # Establezca un pasword para la interfaz de administración de usuarios
      - PASSWORD=proyecto_FC
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.0.0.x
      - WG_DEFAULT_DNS=8.8.8.8
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=3 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
